version: '3.8'
services:
  db:
    container_name: parkme
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports: 
      - '8080:8080'

volumes:
  db:
    driver: local
